#ifndef PINOS_H_
#define PINOS_H_

#include <asf.h>

#define PIN_ASK_IN    IOPORT_CREATE_PIN(IOPORT_PORTA, 0)
#define PIN_FSK_PSK_IN    IOPORT_CREATE_PIN(IOPORT_PORTA, 1)
#define PIN_LED_GRN    IOPORT_CREATE_PIN(IOPORT_PORTA, 2)
#define PIN_LED_RED    IOPORT_CREATE_PIN(IOPORT_PORTA, 3)
#define PIN_FSK_PSK_AC_IN    IOPORT_CREATE_PIN(IOPORT_PORTA, 4)
#define PIN_ASK_AC_IN    IOPORT_CREATE_PIN(IOPORT_PORTA, 5)
#define PIN_125KHZ    IOPORT_CREATE_PIN(IOPORT_PORTA, 7)
#define PIN_D0_TX_CLK    IOPORT_CREATE_PIN(IOPORT_PORTA, 8)
#define PIN_D1_DATA    IOPORT_CREATE_PIN(IOPORT_PORTA, 9)
#define PIN_CARD_PRES    IOPORT_CREATE_PIN(IOPORT_PORTA, 10)
#define PIN_LED_INPUT    IOPORT_CREATE_PIN(IOPORT_PORTA, 11)
#define PIN_MIFARE_RST    IOPORT_CREATE_PIN(IOPORT_PORTA, 16)
#define PIN_MS_BUZZ    IOPORT_CREATE_PIN(IOPORT_PORTA, 17)
#define PIN_MIFARE_SDA    IOPORT_CREATE_PIN(IOPORT_PORTA, 22)
#define PIN_MIFARE_SCL    IOPORT_CREATE_PIN(IOPORT_PORTA, 23)
#define PIN_BUZZ    IOPORT_CREATE_PIN(IOPORT_PORTA, 25)

#endif /* PINOS_H_ */